/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshDashboardRouteImport } from './routes/api/public/hooks/refresh-dashboard'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshDashboardRoute =
  ApiPublicHooksRefreshDashboardRouteImport.update({
    id: '/api/public/hooks/refresh-dashboard',
    path: '/api/public/hooks/refresh-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/scoring': typeof ScoringRoute
  '/workforce': typeof WorkforceRoute
  '/api/public/hooks/refresh-dashboard': typeof ApiPublicHooksRefreshDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/scoring': typeof ScoringRoute
  '/workforce': typeof WorkforceRoute
  '/api/public/hooks/refresh-dashboard': typeof ApiPublicHooksRefreshDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRoute
  '/chat': typeof ChatRoute
  '/map': typeof MapRoute
  '/reports': typeof ReportsRoute
  '/scoring': typeof ScoringRoute
  '/workforce': typeof WorkforceRoute
  '/api/public/hooks/refresh-dashboard': typeof ApiPublicHooksRefreshDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capabilities'
    | '/chat'
    | '/map'
    | '/reports'
    | '/scoring'
    | '/workforce'
    | '/api/public/hooks/refresh-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/chat'
    | '/map'
    | '/reports'
    | '/scoring'
    | '/workforce'
    | '/api/public/hooks/refresh-dashboard'
  id:
    | '__root__'
    | '/'
    | '/capabilities'
    | '/chat'
    | '/map'
    | '/reports'
    | '/scoring'
    | '/workforce'
    | '/api/public/hooks/refresh-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  ChatRoute: typeof ChatRoute
  MapRoute: typeof MapRoute
  ReportsRoute: typeof ReportsRoute
  ScoringRoute: typeof ScoringRoute
  WorkforceRoute: typeof WorkforceRoute
  ApiPublicHooksRefreshDashboardRoute: typeof ApiPublicHooksRefreshDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-dashboard': {
      id: '/api/public/hooks/refresh-dashboard'
      path: '/api/public/hooks/refresh-dashboard'
      fullPath: '/api/public/hooks/refresh-dashboard'
      preLoaderRoute: typeof ApiPublicHooksRefreshDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  ChatRoute: ChatRoute,
  MapRoute: MapRoute,
  ReportsRoute: ReportsRoute,
  ScoringRoute: ScoringRoute,
  WorkforceRoute: WorkforceRoute,
  ApiPublicHooksRefreshDashboardRoute: ApiPublicHooksRefreshDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
